eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
