info:
  name: ${spring.application.name}

spring:
  rabbitmq:
    username: knfncoapp
    password: gifythY2VwviipYDFAQH
    host: localhost
    virtual-host: knfn
  sleuth:
    log:
      json:
        enabled: true
  zipkin:
    host: ${DOCKER_IP}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'

---

spring:
  profiles: cloud
  rabbitmq:
    host: 52.29.74.215.xip.io
    username: guest
    password: guest
    virtual-host: /

info:
  index: ${cf.instance_index}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${instance.guid}:${spring.application.name}:${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://eureka-server.52.29.74.215.xip.io/eureka/
