
info:
  name: ${spring.application.name}

eureka:
  instance:
    hostname: ${cf.instance.ip:localhost}
    nonSecurePort: ${cf.instance.port:80}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${instance.guid}:${spring.application.name}:${server.port:8080}

  client:
    serviceUrl:
      defaultZone: ${vcap.application.application_uris[0]:http://localhost:8761}/eureka/

---

spring:
  profiles: cloud

info:
  index: ${cf.instance_index}
