info:
  name: ${spring.application.name}

spring:
  rabbitmq:
    username: knfncoapp
    password: gifythY2VwviipYDFAQH
    host: localhost
    virtual-host: knfn
  sleuth:
    log:
      json:
        enabled: true
  zipkin:
    host: ${DOCKER_IP}

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'

---

spring:
  profiles: cloud
  rabbitmq:
    host: 52.29.74.215.xip.io
    username: guest
    password: guest
    virtual-host: /

info:
  index: ${cf.instance_index}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:${SERVER_PORT:8761}}/eureka/
