
info:
  name: ${spring.application.name}

---

spring:
  profiles: lattice

info:
  index: ${vcap.application.instance_id}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.eureka-server.credentials.uri:http://localhost:8761}/eureka/
