
info:
  name: ${spring.application.name}
  index: ${vcap.application.instance_id}

---

spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/
